config/routes.rb
GSP::Application.routes.draw do
  namespace :admin do
    get "clients/index"
    post "clients/add_organization"
    get "clients/view/:id", :to => "clients#view", :as => "clients_view_organization"
    post "clients/:organization_id/add_user", :to => "clients#add_user", :as => "clients_add_user"
    delete "clients/:organization_id/delete_user/:user_id", :to => "clients#delete_user", :as => "clients_delete_user"
    delete "clients/:id/delete_organization", :to => "clients#delete_organization", :as => "clients_delete_organization"
    post "clients/:organization_id/purchase_template", :to => "clients#purchase_template", :as => "clients_purchase_template"
  end

  namespace :trial do
    get  "sign_up/index"
    post "sign_up/new_password"

    get "sign_up/form"
    post "sign_up/register_new_user", :as => "register_new_user"
    get "sign_up/already_registered"
    get "sign_up/welcome"
    get "sign_up/setup_organizations"
    get "sign_up/setup_users"

    get "organization/new"
    post "organization/create", :as => "create_new_organization"
  end

  namespace :cfsi do
    get "cmrt/index"
    get "cmrt/show/:id", :to => "cmrt#show"
    post "cmrt/new"
    post "cmrt/validate/:batch_id", :to => "cmrt#validate"
    post "cmrt/validate_zip/:batch_id", :to => "cmrt#validate_zip"
    get "cmrt/list_validation_statuses/:batch_id", :to => "cmrt#list_validation_statuses"
    get "cmrt/download/:id", :to => "cmrt#download"

    get "reports/aggregated_declarations/:batch_id", :to => "reports#aggregated_declarations"
    get "reports/consolidated_smelters/:batch_id", :to => "reports#consolidated_smelters"

    get "compliant_smelters/list"
    post "compliant_smelters/update"

    get "smelters_reference/list"
    post "smelters_reference/update"
  end
  
  namespace :roadmap do
    get "reports/comprehensive_due_diligence/:review_id", :to => "reports#comprehensive_due_diligence", :as => "comprehensive_report"
    get "logos/get/:id", :to => "logos#get", :as => "agency_logo"
  end

  get "reviews/list"

  get "reviews/show"

  get "calendar/show"

  get "reports/list"

  get "reports/view"

  get "help/initial_usage"

  get "templates/list"

  # Home
  #root :to => 'home#index'
  root :to => 'home#reviews'
  get "reviews", :to => 'home#reviews', :as => 'home_reviews'
  get "index", :to => 'home#index', :as => 'home'
  get "test", :to => 'home#panel_test'

  devise_for :users, :controllers => { :sessions => :sessions }

  # GSP Template Manager javascript
  put "organization_templates/:id/update_attributes", :to => "templates#ot_update_attributes"
  put "organization_templates/:id/update_task/:task_sequence", :to => "templates#ot_update_task"
  put "gsp_templates/:id/update_attributes", :to => "templates#gspt_update_attributes"
  put "gsp_templates/:id/update_task/:task_sequence", :to => "templates#gspt_update_task"
  put "review_templates/:id/update_attributes", :to => "templates#review_update_attributes"

  # Template editing
  get "templates/temp_show(/:t_id(/:ot_id))", :to => 'templates#temporary_template_display'
  get "organization_template/:ot_id/new_task", :to => 'templates#new_task'
  get "gsp_template/:t_id/new_task", :to => 'templates#new_task'
  delete "organization_template/:ot_id/:task_sequence/destroy_task", :to => 'templates#destroy_task'
  delete "gsp_template/:t_id/:task_sequence/destroy_task", :to => 'templates#destroy_task'
  get "templates/field_options/:field_name", :to => 'templates#field_options'

    # New 'Standard' model
    get "template/show_readonly/:id", :to => 'templates#show_readonly'
    get "admin/gsp_templates/show_readonly/:id", :to => "admin/gsp_templates#show_readonly"
    put "template/update/:id", :to => 'templates#update', :as => 'update_organization_template'
    put "admin/gsp_templates/update/:id", :to => 'admin/gsp_templates#update', :as => 'update_gsp_template'


  # Organization Templates
  get "template/list", :to => 'templates#list'
  get "template/show/:id", :to => 'templates#show', :as => 'template_show'
  post "template/deploy_review", :to => 'templates#deploy_review', :as => 'deploy_review'
  get "template/:id/prepare_review", :to => "templates#prepare_review", :as => 'prepare_review'
  get "template/settings/:id", :to => "templates#settings", :as => 'template_settings'
  put "template/set_recurrence/:id", :to => "templates#set_recurrence", :as => "template_set_recurrence"
  get "template/new", :to => "templates#new_organization_template", :as => 'new_organization_template'
  post "template/create", :to => "templates#create"
  get "template/send_ical/:id", :to => "templates#send_ical", :as => 'send_ical'

  # GSP Templates
  get "admin/gsp_templates/index", :to => "admin/gsp_templates#index", :as => 'admin_templates'
  get "admin/gsp_templates/list", :to => "admin/gsp_templates#list", :as => 'admin_list_templates'
  get "admin/gsp_templates/new", :to => "admin/gsp_templates#new", :as => 'admin_new_template'
  post "admin/gsp_templates/create", :to => "admin/gsp_templates#create"
  get "admin/gsp_templates/show/(:id)", :to => "admin/gsp_templates#show", :as => "admin_template_show"

  # Review
  get "review/show/:id", :to => "review#show", :as => "show_review"
  get "review/list", :to => "review#list", :as => "list_reviews"
  get "review/task_list/:id", :to => "review#task_list", :as => "list_tasks"

  get "review/task/:id/show", :to => "review#show_task", :as => "task_show"
  get "tasks/active", :to => "review#active_tasks", :as => "active_tasks"
  post "tasks/mark_completed/:id(/:status)", :to => "review#mark_task_as_completed", :as => 'mark_task_completed'
  post "tasks/reopen/:id", :to => "review#reopen_task", :as => 'reopen_task'
  get "tasks/recently_completed_tasks", :to => "review#recently_completed_tasks", :as => 'recently_completed_tasks'

  post "review/task/:id/comment/post", :to => "review#post_comment", :as => "post_comment"
  get  "review/task/comment/:id/show", :to => "review#show_comment", :as => "show_comment"
  get  "review/task/:task_id/comment/form", :to => "review#post_comment_form", :as => "post_comment_form"

  get "review/get_file/:id", :to => "review#get_attachment", :as => "get_file"

  # Calendar
  get "calendar/datafeed/:method", :to => "calendar#datafeed"
  post "calendar/datafeed/:method", :to => "calendar#datafeed"

  # Store


  # Organization
  get "organization/index", :to => 'organization#index'
  get "organization/hierarchy", :to => 'organization#hierarchy', :as => 'organization_hierarchy'
  get "organization/overview",  :to => 'organization#overview',  :as => 'organization_overview'
  get "organization/templates",  :to => 'organization#templates',  :as => 'organization_templates'

    # Review
    get "organization/deployable_list",  :to => 'organization#deploy_reviews',  :as => 'deployable_list'
    get "organization/generate_review/:purchased_template_id",  :to => 'organization#generate_review',  :as => 'generate_review'
    put "organization/update_review/:review_id", :to => 'organization#update_review'
    get "organization/deployed_reviews", :to => 'organization#deployed_reviews', :as => 'deployed_reviews'

  post "organization/share_template/:purchased_template_id", :to => 'organization#share_template', :as => 'share_template'
end

app/models/trial/trial_user.rb
class Trial::TrialUser < User
  validate :email_cannot_contain_a_forbidden_domain, :email_domain_cannot_exist
  after_initialize do |trial_user|
    trial_user.trial_created_at = Time.now
  end

  def self.trial_period
    2.weeks
  end

  def self.forbidden_domains
    %w(gmail yahoo hotmail outlook hushmail aol gmx inbox)
  end

  def email_cannot_contain_a_forbidden_domain
    domain = email.split("@").last
    Trial::TrialUser.forbidden_domains.each do |fd|
      if domain.to_s.include?(fd)
        errors.add(:email, " from '#{domain}' is invalid. Please use your company's email address.")
        break
      end
    end
  end

  def email_domain_cannot_exist
    domain = email.split('@').last
    if domain != "greenstatuspro.com" &&
      !Trial::TrialUser.where("email LIKE ?", "%@#{domain}").where((self.id) ? "id <> ?" : "id IS NOT ?", self.id).empty?
      errors.add(:email, "domain '#{domain}' has been previously registered") unless errors.full_messages.include?("Email has already been taken")
      return false
    end
  end
end

app/controllers/trial/organization_controller.rb
class Trial::OrganizationController < ApplicationController
  def new
    @organization = Organization.new
  end

  def create
    @organization = Organization.new params[:organization]
    current_user.organization = @organization
    if @organization.save && current_user.save
      flash[:notice] = ["Created #{@organization.name}"]
      redirect_to :controller => 'cfsi/cmrt', :action => 'index'
    else
      flash[:alert] = @organization.errors.messages.merge(current_user.errors.messages)
      redirect_to :back
    end
  end
end

app/controllers/trial/public_controller.rb
class Trial::PublicController < ActionController::Base
  layout "trial/public"
end

app/controllers/trial/registrations_controller.rb
class RegistrationsController < Devise::RegistrationsController

  def create
    super
    UserMailer.welcome(@user).deliver unless @user.invalid?
  end

end

app/controllers/trial/sign_up_controller.rb
class Trial::SignUpController < Trial::PublicController
  layout "application"

  def index
  end

  def new_password
    @email = params[:email]
    @user  = Trial::TrialUser.new :email => params[:email], :password => params[:password]
  end

  def form
    @user = Trial::TrialUser.new
  end

  def register_new_user
    @user = Trial::TrialUser.new(params[:trial_trial_user])

    if @user.save
      sign_in @user
      Notifications::Security.welcome(@user).deliver
      Notifications::Security.notify_gsp_of_new_trial_user(@user).deliver
      redirect_to root_url
    else
      flash[:errors] = @user.errors
      redirect_to :action => :already_registered
    end
  end

  def already_registered
  end

  def welcome
    unless request.referer.to_s.match("register_new_user")
      redirect_to :action => :form
    end
  end

  def setup_organizations
  end

  def setup_users
  end

end

app/helpers/trial/sign_up_helper.rb
module Trial::SignUpHelper
end

app/views/trial/sign_up/already_registered.html.erb
<div>
  <p>If your domain or email has already been registered, please <a href="mailto:info@greenstatuspro.com">contact Green Status Pro</a></p>
</div>

<script>
  $("#content").dialog({
    width:400,
    modal:true,
    title:"Attention",
    buttons: [{text: "Try again", click: function() { location.href = "<%= trial_sign_up_form_path %>"; }},
              {text: "Sign in", click: function() { location.href = "<%= new_user_session_path %>"; }}]
  });
</script>

app/views/trial/sign_up/form.html.erb
<script>
$(function() {
  $( "#sign_up_form" ).dialog({
    height: 250,
    modal: true
  });
});
</script>

<div id="sign_up_form" title="Create trial account">
  <%= form_for(@user, :url => trial_register_new_user_path) do |f| %>
    <%= f.label :email %><br />
    <%= f.text_field :email, :value => @user.email %>
    <br />
    <%= f.label :password %><br />
    <%= f.password_field :password %>
    <br />
    <%= f.label :password_confirmation %><br />
    <%= f.password_field :password_confirmation %>

    <%= f.submit "Create Account" %>
  <% end %>
</div>

app/views/trial/sign_up/index.html.erb
<div id="sign_up">
  <div class="header">
    <span class="logo"><img src=""></span>
    <span>
      <p>Already have an account?</p>
      <span><a href="/users/"></a></span>
    </span>
  </div>

  <div class="page">
    <div class="left-column">
      <h1>14-day Trial</h1>
      <p>Process up to 8 CFSI templates and generate reports for your company's SEC Form SD filing.</p>
      <p>And access Roadmap™ for your due diligence requirements.</p>
      <div class="email-form-container">
        <%= form_tag(trial_sign_up_new_password_path, :method => :post, :id => "sign_up_form") do %>
          <%= email_field_tag :email %>
          <%= submit_tag "Sign up" %>
        <% end %>
      </div>
    </div>
    <div class="right-column">
      <div class="info-slider">
      </div>
    </div>
  </div>

  <div class="footer">
    <span><p>&copy; Green Status Pro 2013-14</p></span>
    <span><a href="#" id="contact_us_link">Contact Us</a></span>
    <span><a href="http://www.greenstatuspro.com/#!about-us/c1bda" target="_blank">About Us</a></span>
  </div>
</div>

<%= javascript_include_tag "gsp/trial/gsp.trial.signup" %>

<div id="dialog_boxes" style="display:none">
  <div id="contact_us_form">
  <form>
    <label>From:</label> <input type="text">
    <label>Subject:</label> <input type="text">
    <textarea></textarea>
    <input type="submit" value="Send">
  </form>
  </div>

  <div id="invalid_email">
    <p><span>Invalid email address</span></p>
  </div>
</div>

app/views/trial/sign_up/is_domain_already_registered.html.erb
<h1>Trial::SignUp#is_domain_already_registered</h1>
<p>Find me in app/views/trial/sign_up/is_domain_already_registered.html.erb</p>

app/views/trial/sign_up/new_password.html.erb
<div id="new_password">
  <div id="left_column">
    <%= form_tag("") do %>
      <%= text_field_tag :email, @email %>
      <%= password_field_tag :password %>
      <%= password_field_tag :password_confirmation %>
      <%= text_field_tag :first_name %>
      <%= text_field_tag :last_name %>
      <%= submit_tag "Sign up" %>
    <% end %>
  </div>

  <div id="right_column">
  </div>
</div>

app/views/trial/sign_up/register_new_user.html.erb
<h1>Trial::SignUp#register_new_user</h1>
<p>Find me in app/views/trial/sign_up/register_new_user.html.erb</p>

app/views/trial/sign_up/setup_organizations.html.erb
<h1>Trial::SignUp#setup_organizations</h1>
<p>Find me in app/views/trial/sign_up/setup_organizations.html.erb</p>

app/views/trial/sign_up/setup_users.html.erb
<h1>Trial::SignUp#setup_users</h1>
<p>Find me in app/views/trial/sign_up/setup_users.html.erb</p>

app/views/trial/sign_up/welcome.html.erb
<h1>Trial::SignUp#welcome</h1>
<p>Find me in app/views/trial/sign_up/welcome.html.erb</p>