config/routes.rb
GSP::Application.routes.draw do
  namespace :admin do
    get "clients/index"
    post "clients/add_organization"
    get "clients/view/:id", :to => "clients#view", :as => "clients_view_organization"
    post "clients/:organization_id/add_user", :to => "clients#add_user", :as => "clients_add_user"
    delete "clients/:organization_id/delete_user/:user_id", :to => "clients#delete_user", :as => "clients_delete_user"
    delete "clients/:id/delete_organization", :to => "clients#delete_organization", :as => "clients_delete_organization"
    post "clients/:organization_id/purchase_template", :to => "clients#purchase_template", :as => "clients_purchase_template"
  end

  namespace :trial do
    get  "sign_up/index"
    post "sign_up/new_password"

    get "sign_up/form"
    post "sign_up/register_new_user", :as => "register_new_user"
    get "sign_up/already_registered"
    get "sign_up/welcome"
    get "sign_up/setup_organizations"
    get "sign_up/setup_users"

    get "organization/new"
    post "organization/create", :as => "create_new_organization"
  end

  namespace :cfsi do
    get "cmrt/index"
    get "cmrt/show/:id", :to => "cmrt#show"
    post "cmrt/new"
    post "cmrt/validate/:batch_id", :to => "cmrt#validate"
    post "cmrt/validate_zip/:batch_id", :to => "cmrt#validate_zip"
    get "cmrt/list_validation_statuses/:batch_id", :to => "cmrt#list_validation_statuses"
    get "cmrt/download/:id", :to => "cmrt#download"

    get "reports/aggregated_declarations/:batch_id", :to => "reports#aggregated_declarations"
    get "reports/consolidated_smelters/:batch_id", :to => "reports#consolidated_smelters"

    get "compliant_smelters/list"
    post "compliant_smelters/update"

    get "smelters_reference/list"
    post "smelters_reference/update"
  end
  
  namespace :roadmap do
    get "reports/comprehensive_due_diligence/:review_id", :to => "reports#comprehensive_due_diligence", :as => "comprehensive_report"
    get "logos/get/:id", :to => "logos#get", :as => "agency_logo"
  end

  get "reviews/list"

  get "reviews/show"

  get "calendar/show"

  get "reports/list"

  get "reports/view"

  get "help/initial_usage"

  get "templates/list"

  # Home
  #root :to => 'home#index'
  root :to => 'home#reviews'
  get "reviews", :to => 'home#reviews', :as => 'home_reviews'
  get "index", :to => 'home#index', :as => 'home'
  get "test", :to => 'home#panel_test'

  devise_for :users, :controllers => { :sessions => :sessions }

  # GSP Template Manager javascript
  put "organization_templates/:id/update_attributes", :to => "templates#ot_update_attributes"
  put "organization_templates/:id/update_task/:task_sequence", :to => "templates#ot_update_task"
  put "gsp_templates/:id/update_attributes", :to => "templates#gspt_update_attributes"
  put "gsp_templates/:id/update_task/:task_sequence", :to => "templates#gspt_update_task"
  put "review_templates/:id/update_attributes", :to => "templates#review_update_attributes"

  # Template editing
  get "templates/temp_show(/:t_id(/:ot_id))", :to => 'templates#temporary_template_display'
  get "organization_template/:ot_id/new_task", :to => 'templates#new_task'
  get "gsp_template/:t_id/new_task", :to => 'templates#new_task'
  delete "organization_template/:ot_id/:task_sequence/destroy_task", :to => 'templates#destroy_task'
  delete "gsp_template/:t_id/:task_sequence/destroy_task", :to => 'templates#destroy_task'
  get "templates/field_options/:field_name", :to => 'templates#field_options'

    # New 'Standard' model
    get "template/show_readonly/:id", :to => 'templates#show_readonly'
    get "admin/gsp_templates/show_readonly/:id", :to => "admin/gsp_templates#show_readonly"
    put "template/update/:id", :to => 'templates#update', :as => 'update_organization_template'
    put "admin/gsp_templates/update/:id", :to => 'admin/gsp_templates#update', :as => 'update_gsp_template'


  # Organization Templates
  get "template/list", :to => 'templates#list'
  get "template/show/:id", :to => 'templates#show', :as => 'template_show'
  post "template/deploy_review", :to => 'templates#deploy_review', :as => 'deploy_review'
  get "template/:id/prepare_review", :to => "templates#prepare_review", :as => 'prepare_review'
  get "template/settings/:id", :to => "templates#settings", :as => 'template_settings'
  put "template/set_recurrence/:id", :to => "templates#set_recurrence", :as => "template_set_recurrence"
  get "template/new", :to => "templates#new_organization_template", :as => 'new_organization_template'
  post "template/create", :to => "templates#create"
  get "template/send_ical/:id", :to => "templates#send_ical", :as => 'send_ical'

  # GSP Templates
  get "admin/gsp_templates/index", :to => "admin/gsp_templates#index", :as => 'admin_templates'
  get "admin/gsp_templates/list", :to => "admin/gsp_templates#list", :as => 'admin_list_templates'
  get "admin/gsp_templates/new", :to => "admin/gsp_templates#new", :as => 'admin_new_template'
  post "admin/gsp_templates/create", :to => "admin/gsp_templates#create"
  get "admin/gsp_templates/show/(:id)", :to => "admin/gsp_templates#show", :as => "admin_template_show"

  # Review
  get "review/show/:id", :to => "review#show", :as => "show_review"
  get "review/list", :to => "review#list", :as => "list_reviews"
  get "review/task_list/:id", :to => "review#task_list", :as => "list_tasks"

  get "review/task/:id/show", :to => "review#show_task", :as => "task_show"
  get "tasks/active", :to => "review#active_tasks", :as => "active_tasks"
  post "tasks/mark_completed/:id(/:status)", :to => "review#mark_task_as_completed", :as => 'mark_task_completed'
  post "tasks/reopen/:id", :to => "review#reopen_task", :as => 'reopen_task'
  get "tasks/recently_completed_tasks", :to => "review#recently_completed_tasks", :as => 'recently_completed_tasks'

  post "review/task/:id/comment/post", :to => "review#post_comment", :as => "post_comment"
  get  "review/task/comment/:id/show", :to => "review#show_comment", :as => "show_comment"
  get  "review/task/:task_id/comment/form", :to => "review#post_comment_form", :as => "post_comment_form"

  get "review/get_file/:id", :to => "review#get_attachment", :as => "get_file"

  # Calendar
  get "calendar/datafeed/:method", :to => "calendar#datafeed"
  post "calendar/datafeed/:method", :to => "calendar#datafeed"

  # Store


  # Organization
  get "organization/index", :to => 'organization#index'
  get "organization/hierarchy", :to => 'organization#hierarchy', :as => 'organization_hierarchy'
  get "organization/overview",  :to => 'organization#overview',  :as => 'organization_overview'
  get "organization/templates",  :to => 'organization#templates',  :as => 'organization_templates'

    # Review
    get "organization/deployable_list",  :to => 'organization#deploy_reviews',  :as => 'deployable_list'
    get "organization/generate_review/:purchased_template_id",  :to => 'organization#generate_review',  :as => 'generate_review'
    put "organization/update_review/:review_id", :to => 'organization#update_review'
    get "organization/deployed_reviews", :to => 'organization#deployed_reviews', :as => 'deployed_reviews'

  post "organization/share_template/:purchased_template_id", :to => 'organization#share_template', :as => 'share_template'
end

app/models/cfsi/reports.rb
module Cfsi::Reports
  def self.table_name_prefix
    'cfsi_reports_'
  end
end

app/controllers/cfsi/reports_controller.rb
class Cfsi::ReportsController < ApplicationController
  def report_filename(name)
    [current_user.organization.name, Time.now.strftime("%Y%m%d%H%M%S"), current_user.eponym, name].join('_-_').gsub(/[^\w,\s-\.]/, '').gsub(' ', '_')
  end

  def aggregated_declarations
    batch = Cfsi::ValidationsBatch.includes([:unidentified_cmrt_validations, :vendor_cmrt_validations => [:vendor, :spreadsheet, {:cmrt => [:minerals_vendor, {:declaration => :mineral_smelters}]}]]).find(params[:batch_id])
    spreadsheet = GSP::Protocols::Regulations::CFSI::Reports::Excel::AggregatedDeclarations.new(batch).to_excel
    send_data spreadsheet.to_stream(false).read, :filename => report_filename("cfsi_aggregated_declarations_report.gsp.xlsx"), :type => 'application/excel'
  end

  def consolidated_smelters
    batch = Cfsi::ValidationsBatch.includes([:unidentified_cmrt_validations, :vendor_cmrt_validations => [:vendor, :spreadsheet, {:cmrt => [:minerals_vendor, {:declaration => :mineral_smelters}]}]]).find(params[:batch_id])
    spreadsheet = GSP::Protocols::Regulations::CFSI::Reports::Excel::ConsolidatedSmelters.new(batch).to_excel
    send_data spreadsheet.to_stream(false).read, :filename => report_filename("cfsi_consolidated_smelters_report.gsp.xlsx"), :type => 'application/excel'
  end
end

app/controllers/reports/roadmap_controller.rb
require 'prawn'
require "prawn/measurement_extensions"

class RoadmapController < ApplicationController
  include ReportsHelper

  def comprehensive_due_diligence
    review = Review.includes({:tasks => :comments}).where(:id => params[:id], :organization_id => current_user.organization.id).first

    storage_path = File.join(current_user.storage_path, "comprehensive_due_diligence_report_test.pdf")
    FileUtils.mkdir_p(current_user.storage_path)

    Prawn::Document.generate(storage_path) do

      # Top strip
      bounding_box([-0.5.in, 9.75.in], :width => 8.in, :height => 1.in) do
        # Header strip
        fill_color "A1693B"
        fill_rectangle [0, 1.75.in], 8.5.in, 1.in

        fill_color "FFCFA6"
        text "Report created: #{Time.now.to_formatted_s(:review_date)}", :align => :right, :size => 9
      end

      # Header
      bounding_box([0, 9.25.in], :width => 7.5.in, :height => 1.25.in) do
        fill_color "222222"
        text review.organization.name, :align => :center, :size => 14, :style => :bold
        move_down 20
        text review.name, :align => :left, :size => 12, :style => :bold
        text "Due: #{review.targeted_completion_at.to_formatted_s(:review_date)}", :align => :left, :size => 12, :style => :bold

        transparent(0.5) do
          image File.join(Rails.root, "public/images/logo.jpg"), :at => [5.5.in, 1.25.in], :scale => 0.66
        end
      end

      # Tasks
      review.tasks.each do |task|
        # Header
        sequence = make_cell(:content => "<font size='14'><b>#{task.sequence}</b></font>", :rowspan => 2, :valign => :center)
        header   = [sequence, "<font size='10'><b>Reviewer</b></font>", "<font size='10'><b>Start Date</b></font>", "<font size='10'><b>Completion Date</b></font>"]
        hdr_info = ["<font size='9'>%s</font>" % task.reviewer.eponym,
                    "<font size='9'>%s</font>" % ((task.start_at) ? task.start_at.to_formatted_s(:review_date) : 'Not started'),
                    "<font size='9'>%s</font>" % ((task.actual_completion_at) ? task.actual_completion_at.to_formatted_s(:review_date) : '')]

        # Instructions
        task_name = make_cell(:content => "<b>#{task.name}</b>", :align => :center)
        task_inst = make_cell(:content => "<font size='9'>%s</font>" % task.instructions.gsub('<li>', '- ').gsub('</li>', ""), :align => :left)

        # Comments
        comments = []
        task.comments.each do |comment|
          author = "<b>%s:</b>" % comment.author.eponym
          date   = "<font size='8'>%s</font>\n" % comment.created_at.to_formatted_s(:long)
          body   = "<font size='9'>%s</font>" % comment.body.gsub(/<\/.+>/, '').gsub(/<.+>/, '')
          attachments = "<font size='9'>Attachments: %s</font>" % comment.attachments.map { |a| "<color rgb='0000FF'><u><link href='%s'>%s</link></u></color>" % ["http://gsp-app.greenstatuspro.com/review/get_file/#{a.id}", a.filename] }.join(', ')
          comments += [[""], [[author, date, body, attachments].join("\n")]]
        end

        header_table = make_table([header, hdr_info], :column_widths => {0 => 30}, :width => 7.40.in, :position => :center, :cell_style => {:inline_format => true, :align => :center, :border_color => "CCCCCC", :background_color => "FAFAFA"})
        instructions_table = make_table([[task_name], [task_inst]], :width => 7.40.in, :position => :left, :cell_style => {:inline_format => true, :align => :left, :border_width => 0})
        comments_table = make_table(comments, :width => 7.40.in, :position => :left, :cell_style => {:inline_format => true, :align => :left, :border_width => 0})

        table([[header_table], [instructions_table], [comments_table]], :position => :center, :header => true, :width => 7.40.in, :cell_style => {:border_color => "CCCCCC"})
        move_down 15
      end

    end

    send_data File.read(storage_path), :filename => report_filename(File.basename(storage_path)), :type => 'application/pdf'
  end

end

app/helpers/reports_helper.rb
module ReportsHelper
  def report_filename(name)
    [current_user.organization.name, Time.now.strftime("%Y%m%d%H%M%S"), current_user.eponym, name].join('_-_').gsub(/[^\w,\s-\.]/, '').gsub(' ', '_')
  end

  def worksheet_header(worksheet, style)
    worksheet.add_image(:image_src => File.expand_path("../../public/images/logo.jpg", File.dirname(__FILE__)), :noSelect => true, :noMove => true) do |image|
     image.width  = 4
     image.height = 3

     image.start_at 0, 0
     image.end_at 2, 1
    end

    worksheet.add_row(["", "",[worksheet.name,
                              "%s: %s" % ["Co.".rjust(6, ' '), current_user.organization.name],
                              "%s: %s" % ["Date".rjust(6, ' '), Date.today],
                              "%s: %s" % ["Time".rjust(6, ' '), Time.now.strftime("%H:%M:%S")],
                              "%s: %s" % ["User".rjust(6, ' '), current_user.eponym]
                              ].join("\n")], :style => style).height = 65.0

    worksheet.merge_cells "A1:B1"
    worksheet.merge_cells "C1:E1"

    # Freeze pane over data rows
    worksheet.sheet_view.pane do |pane|
      pane.top_left_cell = "A3"
      pane.state = :frozen_split
      pane.y_split = 2
      pane.x_split = 0
      pane.active_pane = :bottom_right
    end
  end
end

app/views/reports/comprehensive.html.erb
<div class="panel" id="task-panel" style="width:90%">
  <h2>Your Organization's Reviews</h2>
  <div>
    <table>
      
      <% if @reviews.empty? %>
      <tr>
        <td colspan="3" align="center">No reviews</td>
      </tr>
      <% else %>
      <tr>
        <th>Agency</th>
        <th>Name</th>
        <th>Due Date</th>
        <th>Completion Date</th>
      </tr>
      <% @reviews.each do |review| %>
      <tr class="panel-table-row">
        <td align="center"><% if review.agency; %><span title="<%= review.agency.name %>" style="font-size:.8em"><%= review.organization_template.agency.acronym %></span><% ; end %></td>
        <td align="center"><%= link_to review.name, comprehensive_report_path(review.id), :target => '_new' %></td>
        <td align="center">
          <span style="font-size:.8em"><%= review.targeted_completion_at.to_formatted_s(:review_date) %></span>
        </td>
        <td align="center" nowrap><%= (review.actual_completion_at) ? review.actual_completion_at.to_formatted_s(:review_date) : '' %></td>
      </tr>
      <% end %>
      <% end %>
    </table>
  </div>
</div>

app/views/reports/generate_comprehensive.html.erb
<!--  -->

<div id="report_page">
  <div id="report_header">
    <p><%= Time.now.to_formatted_s(:review_date) %></p>
  </div>
  
  <div id="report_attributes">
    <div id="report_company"><h2><%= @review.organization.full_name %></h2></div>
    <div id="report_logos">
      <div id="report_agency_logo"><% if @review.agency; %><%= @review.agency.logo_image_tag %><% ; end %></div>
      <div id="report_name">
        <h2><%= @review.name %></h2>
        <h3><%= @review.targeted_completion_at.to_formatted_s(:review_date) %></h3>
      </div>
      <div id="report_gsp_logo"><img src="/images/logo.jpg" height="64"></div>
    </div>
    
    
    <% if @review.agency; %><div id="report_objective"><p><%= @review.organization_template.objectives.html_safe %></p></div><% ; end %>
  </div>
  
  <div id="report_tasks">
    <% @review.tasks.each do |task| %>
    <div>
      <div>
        <table>
          <tr>
            <th rowspan="2"><%= task.sequence %></th>
            <th>Reviewer</th>
            <th>Start Date</th>
            <th>Completion Date</th>
          </tr>
          <tr>
            <td><%= task.reviewer.eponym %></td>
            <td><%= (task.start_at) ? task.start_at.to_formatted_s(:review_date) : 'Not started' %></td>
            <td><%= (task.actual_completion_at) ? task.actual_completion_at.to_formatted_s(:review_date) : '&nbsp;'.html_safe %></td>
          </tr>
        </table>
      </div>
      <div id="report_task_attributes">
        <div id="report_task">
          <p><strong><%= task.name %></strong></p>
          <p><%= task.instructions.html_safe %></p>
        </div>
        <% task.comments.reverse.each do |comment| %>
        <div id="report_task_comment">
          <span><strong><%= comment.author.eponym %>: </strong> <%= comment.body.html_safe %> </span>
          <p>Attachments: <%= comment.attachments.map { |a| link_to a.filename, get_file_path(a.id) }.join(', ').html_safe %></p>
          <p><%= comment.created_at.to_formatted_s(:long) %></p>
          
        </div>
        <% end %>
      </div>
    </div>
    <% end %>
  </div>
</div>

app/views/reports/list.html.erb
<div>
  <ol>
    <li><%= link_to "Comprehensive Report", comprehensive_list_path %></li>
  </ol>
</div>

app/views/reports/review_status.html.erb
<img src="<%= @graph_image_url %>">

app/views/reports/view.html.erb
<h1>Reports#view</h1>
<p>Find me in app/views/reports/view.html.erb</p>